set.seed(4267)
amostra <- rexp(2072, rate=7.5)
sj <- cumsum(amostra)
T <- ceiling(sj[2072])
subintervalos <- seq(1, T, by=1)
contagem <- table(cut(sj, breaks=subintervalos, right=FALSE))
media_obs <- mean(contagem)
desvio_absoluto <- abs(media_obs - 7.5)
desvio_absoluto <- round(desvio_absoluto, 4)
